export const INTELLIGENCE_EVENTS = {
  LOW_STOCK_PREDICTED: "LOW_STOCK_PREDICTED",
  PURCHASE_RECOMMENDED: "PURCHASE_RECOMMENDED",
  DEAD_STOCK_DETECTED: "DEAD_STOCK_DETECTED",
} as const;
export type IntelligenceEventName =
  (typeof INTELLIGENCE_EVENTS)[keyof typeof INTELLIGENCE_EVENTS];
