/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDoctorsRouteImport } from './routes/_authenticated/doctors'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedPrescriptionsRouteImport } from './routes/_authenticated/prescriptions'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as PlanetPlanetIdRouteImport } from './routes/planet.$planetId'
import { Route as AuthenticatedCatalogIndexRouteImport } from './routes/_authenticated/catalog.index'
import { Route as AuthenticatedCatalogProductIdRouteImport } from './routes/_authenticated/catalog.$productId'
import { Route as AuthenticatedDoctorsDoctorIdRouteImport } from './routes/_authenticated/doctors.$doctorId'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'
import { Route as AuthenticatedPrescriptionsPrescriptionIdRouteImport } from './routes/_authenticated/prescriptions.$prescriptionId'
import { Route as AuthenticatedPurchaseOrdersIdRouteImport } from './routes/_authenticated/purchase-orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDoctorsRoute = AuthenticatedDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrescriptionsRoute =
  AuthenticatedPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlanetPlanetIdRoute = PlanetPlanetIdRouteImport.update({
  id: '/planet/$planetId',
  path: '/planet/$planetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCatalogIndexRoute =
  AuthenticatedCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductIdRoute =
  AuthenticatedCatalogProductIdRouteImport.update({
    id: '/catalog/$productId',
    path: '/catalog/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorsDoctorIdRoute =
  AuthenticatedDoctorsDoctorIdRouteImport.update({
    id: '/$doctorId',
    path: '/$doctorId',
    getParentRoute: () => AuthenticatedDoctorsRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedPrescriptionsPrescriptionIdRoute =
  AuthenticatedPrescriptionsPrescriptionIdRouteImport.update({
    id: '/$prescriptionId',
    path: '/$prescriptionId',
    getParentRoute: () => AuthenticatedPrescriptionsRoute,
  } as any)
const AuthenticatedPurchaseOrdersIdRoute =
  AuthenticatedPurchaseOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPurchaseOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/mission-control': typeof MissionControlRoute
  '/reset-password': typeof ResetPasswordRoute
  '/doctors': typeof AuthenticatedDoctorsRouteWithChildren
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/prescriptions': typeof AuthenticatedPrescriptionsRouteWithChildren
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/planet/$planetId': typeof PlanetPlanetIdRoute
  '/catalog/$productId': typeof AuthenticatedCatalogProductIdRoute
  '/doctors/$doctorId': typeof AuthenticatedDoctorsDoctorIdRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/catalog/': typeof AuthenticatedCatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/mission-control': typeof MissionControlRoute
  '/reset-password': typeof ResetPasswordRoute
  '/doctors': typeof AuthenticatedDoctorsRouteWithChildren
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/prescriptions': typeof AuthenticatedPrescriptionsRouteWithChildren
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/planet/$planetId': typeof PlanetPlanetIdRoute
  '/catalog/$productId': typeof AuthenticatedCatalogProductIdRoute
  '/doctors/$doctorId': typeof AuthenticatedDoctorsDoctorIdRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/catalog': typeof AuthenticatedCatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/mission-control': typeof MissionControlRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/doctors': typeof AuthenticatedDoctorsRouteWithChildren
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/prescriptions': typeof AuthenticatedPrescriptionsRouteWithChildren
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteWithChildren
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/planet/$planetId': typeof PlanetPlanetIdRoute
  '/_authenticated/catalog/$productId': typeof AuthenticatedCatalogProductIdRoute
  '/_authenticated/doctors/$doctorId': typeof AuthenticatedDoctorsDoctorIdRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  '/_authenticated/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/_authenticated/catalog/': typeof AuthenticatedCatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chat'
    | '/auth'
    | '/mission-control'
    | '/reset-password'
    | '/doctors'
    | '/patients'
    | '/prescriptions'
    | '/purchase-orders'
    | '/suppliers'
    | '/warehouses'
    | '/planet/$planetId'
    | '/catalog/$productId'
    | '/doctors/$doctorId'
    | '/patients/$patientId'
    | '/prescriptions/$prescriptionId'
    | '/purchase-orders/$id'
    | '/catalog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/auth'
    | '/mission-control'
    | '/reset-password'
    | '/doctors'
    | '/patients'
    | '/prescriptions'
    | '/purchase-orders'
    | '/suppliers'
    | '/warehouses'
    | '/planet/$planetId'
    | '/catalog/$productId'
    | '/doctors/$doctorId'
    | '/patients/$patientId'
    | '/prescriptions/$prescriptionId'
    | '/purchase-orders/$id'
    | '/catalog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-chat'
    | '/auth'
    | '/mission-control'
    | '/reset-password'
    | '/_authenticated/doctors'
    | '/_authenticated/patients'
    | '/_authenticated/prescriptions'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/suppliers'
    | '/_authenticated/warehouses'
    | '/planet/$planetId'
    | '/_authenticated/catalog/$productId'
    | '/_authenticated/doctors/$doctorId'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/prescriptions/$prescriptionId'
    | '/_authenticated/purchase-orders/$id'
    | '/_authenticated/catalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiChatRoute: typeof AiChatRoute
  AuthRoute: typeof AuthRoute
  MissionControlRoute: typeof MissionControlRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PlanetPlanetIdRoute: typeof PlanetPlanetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/doctors': {
      id: '/_authenticated/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prescriptions': {
      id: '/_authenticated/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AuthenticatedPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/planet/$planetId': {
      id: '/planet/$planetId'
      path: '/planet/$planetId'
      fullPath: '/planet/$planetId'
      preLoaderRoute: typeof PlanetPlanetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/catalog/': {
      id: '/_authenticated/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AuthenticatedCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/$productId': {
      id: '/_authenticated/catalog/$productId'
      path: '/catalog/$productId'
      fullPath: '/catalog/$productId'
      preLoaderRoute: typeof AuthenticatedCatalogProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors/$doctorId': {
      id: '/_authenticated/doctors/$doctorId'
      path: '/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof AuthenticatedDoctorsDoctorIdRouteImport
      parentRoute: typeof AuthenticatedDoctorsRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/prescriptions/$prescriptionId': {
      id: '/_authenticated/prescriptions/$prescriptionId'
      path: '/$prescriptionId'
      fullPath: '/prescriptions/$prescriptionId'
      preLoaderRoute: typeof AuthenticatedPrescriptionsPrescriptionIdRouteImport
      parentRoute: typeof AuthenticatedPrescriptionsRoute
    }
    '/_authenticated/purchase-orders/$id': {
      id: '/_authenticated/purchase-orders/$id'
      path: '/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedPurchaseOrdersRoute
    }
  }
}

interface AuthenticatedDoctorsRouteChildren {
  AuthenticatedDoctorsDoctorIdRoute: typeof AuthenticatedDoctorsDoctorIdRoute
}

const AuthenticatedDoctorsRouteChildren: AuthenticatedDoctorsRouteChildren = {
  AuthenticatedDoctorsDoctorIdRoute: AuthenticatedDoctorsDoctorIdRoute,
}

const AuthenticatedDoctorsRouteWithChildren =
  AuthenticatedDoctorsRoute._addFileChildren(AuthenticatedDoctorsRouteChildren)

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedPrescriptionsRouteChildren {
  AuthenticatedPrescriptionsPrescriptionIdRoute: typeof AuthenticatedPrescriptionsPrescriptionIdRoute
}

const AuthenticatedPrescriptionsRouteChildren: AuthenticatedPrescriptionsRouteChildren =
  {
    AuthenticatedPrescriptionsPrescriptionIdRoute:
      AuthenticatedPrescriptionsPrescriptionIdRoute,
  }

const AuthenticatedPrescriptionsRouteWithChildren =
  AuthenticatedPrescriptionsRoute._addFileChildren(
    AuthenticatedPrescriptionsRouteChildren,
  )

interface AuthenticatedPurchaseOrdersRouteChildren {
  AuthenticatedPurchaseOrdersIdRoute: typeof AuthenticatedPurchaseOrdersIdRoute
}

const AuthenticatedPurchaseOrdersRouteChildren: AuthenticatedPurchaseOrdersRouteChildren =
  {
    AuthenticatedPurchaseOrdersIdRoute: AuthenticatedPurchaseOrdersIdRoute,
  }

const AuthenticatedPurchaseOrdersRouteWithChildren =
  AuthenticatedPurchaseOrdersRoute._addFileChildren(
    AuthenticatedPurchaseOrdersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDoctorsRoute: typeof AuthenticatedDoctorsRouteWithChildren
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
  AuthenticatedPrescriptionsRoute: typeof AuthenticatedPrescriptionsRouteWithChildren
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRouteWithChildren
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
  AuthenticatedCatalogProductIdRoute: typeof AuthenticatedCatalogProductIdRoute
  AuthenticatedCatalogIndexRoute: typeof AuthenticatedCatalogIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDoctorsRoute: AuthenticatedDoctorsRouteWithChildren,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
  AuthenticatedPrescriptionsRoute: AuthenticatedPrescriptionsRouteWithChildren,
  AuthenticatedPurchaseOrdersRoute:
    AuthenticatedPurchaseOrdersRouteWithChildren,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
  AuthenticatedCatalogProductIdRoute: AuthenticatedCatalogProductIdRoute,
  AuthenticatedCatalogIndexRoute: AuthenticatedCatalogIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiChatRoute: AiChatRoute,
  AuthRoute: AuthRoute,
  MissionControlRoute: MissionControlRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PlanetPlanetIdRoute: PlanetPlanetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
