/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YemenDebugRouteImport } from './routes/yemen-debug'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TrackRouteImport } from './routes/track'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrescriptionRouteImport } from './routes/prescription'
import { Route as NetworkTestRouteImport } from './routes/network-test'
import { Route as NetworkHealthRouteImport } from './routes/network-health'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as AiSymptomsRouteImport } from './routes/ai-symptoms'
import { Route as AiSupplementRouteImport } from './routes/ai-supplement'
import { Route as AiPrescriptionRouteImport } from './routes/ai-prescription'
import { Route as AiPharmacistRouteImport } from './routes/ai-pharmacist'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AdminWorkforceRouteImport } from './routes/admin-workforce'
import { Route as AdminSettingsRouteImport } from './routes/admin-settings'
import { Route as AdminRxCheckRouteImport } from './routes/admin-rx-check'
import { Route as AdminProductsRouteImport } from './routes/admin-products'
import { Route as AdminOffersRouteImport } from './routes/admin-offers'
import { Route as AdminMarketingRouteImport } from './routes/admin-marketing'
import { Route as AdminLogsRouteImport } from './routes/admin-logs'
import { Route as AdminInventoryRouteImport } from './routes/admin-inventory'
import { Route as AdminDiscountsRouteImport } from './routes/admin-discounts'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin-diagnostics'
import { Route as AdminCommandRouteImport } from './routes/admin-command'
import { Route as AdminClassificationsRouteImport } from './routes/admin-classifications'
import { Route as AdminCampaignsRouteImport } from './routes/admin-campaigns'
import { Route as AdminBundlesRouteImport } from './routes/admin-bundles'
import { Route as AdminBannersRouteImport } from './routes/admin-banners'
import { Route as AdminBackupsRouteImport } from './routes/admin-backups'
import { Route as AdminAutomationHubRouteImport } from './routes/admin-automation-hub'
import { Route as AdminAiWhatsappRouteImport } from './routes/admin-ai-whatsapp'
import { Route as AdminAiSalesCxRouteImport } from './routes/admin-ai-sales-cx'
import { Route as AdminAiProcurementRouteImport } from './routes/admin-ai-procurement'
import { Route as AdminAiOrchestratorRouteImport } from './routes/admin-ai-orchestrator'
import { Route as AdminAiMarketingRouteImport } from './routes/admin-ai-marketing'
import { Route as AdminAiLoyaltyRouteImport } from './routes/admin-ai-loyalty'
import { Route as AdminAiInventoryRouteImport } from './routes/admin-ai-inventory'
import { Route as AdminAiExecutiveDashboardRouteImport } from './routes/admin-ai-executive-dashboard'
import { Route as AdminAiExecutiveRouteImport } from './routes/admin-ai-executive'
import { Route as AdminAiExcelImportRouteImport } from './routes/admin-ai-excel-import'
import { Route as AdminAiChronicRefillRouteImport } from './routes/admin-ai-chronic-refill'
import { Route as AdminAiCatalogRouteImport } from './routes/admin-ai-catalog'
import { Route as AdminAgentsRouteImport } from './routes/admin-agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ConditionsSlugRouteImport } from './routes/conditions.$slug'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicUptimeWebhookRouteImport } from './routes/api/public/uptime-webhook'
import { Route as ApiPublicLogErrorRouteImport } from './routes/api/public/log-error'
import { Route as ApiPublicIncidentCheckRouteImport } from './routes/api/public/incident-check'
import { Route as ApiPublicImgRouteImport } from './routes/api/public/img'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksWeeklyExecReportRouteImport } from './routes/api/public/hooks/weekly-exec-report'
import { Route as ApiPublicHooksWeeklyAiEnrichRouteImport } from './routes/api/public/hooks/weekly-ai-enrich'
import { Route as ApiPublicHooksRxMirrorRouteImport } from './routes/api/public/hooks/rx-mirror'
import { Route as ApiPublicHooksNightlyIntelRouteImport } from './routes/api/public/hooks/nightly-intel'
import { Route as ApiPublicHooksChronicRefillsRouteImport } from './routes/api/public/hooks/chronic-refills'
import { Route as ApiPublicHooksAlertsWorkerRouteImport } from './routes/api/public/hooks/alerts-worker'
import { Route as ApiPublicHooksAgentsWhatsappRouteImport } from './routes/api/public/hooks/agents/whatsapp'
import { Route as ApiPublicHooksAgentsSalesRouteImport } from './routes/api/public/hooks/agents/sales'
import { Route as ApiPublicHooksAgentsOperationsRouteImport } from './routes/api/public/hooks/agents/operations'
import { Route as ApiPublicHooksAgentsMarketingRouteImport } from './routes/api/public/hooks/agents/marketing'
import { Route as ApiPublicHooksAgentsInventoryRouteImport } from './routes/api/public/hooks/agents/inventory'
import { Route as ApiPublicHooksAgentsCxRouteImport } from './routes/api/public/hooks/agents/cx'
import { Route as ApiPublicHooksAgentsCtoRouteImport } from './routes/api/public/hooks/agents/cto'
import { Route as ApiPublicHooksAgentsCeoRouteImport } from './routes/api/public/hooks/agents/ceo'
import { Route as ApiPublicHooksAgentsBiRouteImport } from './routes/api/public/hooks/agents/bi'

const YemenDebugRoute = YemenDebugRouteImport.update({
  id: '/yemen-debug',
  path: '/yemen-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionRoute = PrescriptionRouteImport.update({
  id: '/prescription',
  path: '/prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkTestRoute = NetworkTestRouteImport.update({
  id: '/network-test',
  path: '/network-test',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkHealthRoute = NetworkHealthRouteImport.update({
  id: '/network-health',
  path: '/network-health',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSymptomsRoute = AiSymptomsRouteImport.update({
  id: '/ai-symptoms',
  path: '/ai-symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSupplementRoute = AiSupplementRouteImport.update({
  id: '/ai-supplement',
  path: '/ai-supplement',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPrescriptionRoute = AiPrescriptionRouteImport.update({
  id: '/ai-prescription',
  path: '/ai-prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPharmacistRoute = AiPharmacistRouteImport.update({
  id: '/ai-pharmacist',
  path: '/ai-pharmacist',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkforceRoute = AdminWorkforceRouteImport.update({
  id: '/admin-workforce',
  path: '/admin-workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRxCheckRoute = AdminRxCheckRouteImport.update({
  id: '/admin-rx-check',
  path: '/admin-rx-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin-products',
  path: '/admin-products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/admin-offers',
  path: '/admin-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/admin-marketing',
  path: '/admin-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin-logs',
  path: '/admin-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin-inventory',
  path: '/admin-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/admin-discounts',
  path: '/admin-discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/admin-diagnostics',
  path: '/admin-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommandRoute = AdminCommandRouteImport.update({
  id: '/admin-command',
  path: '/admin-command',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassificationsRoute = AdminClassificationsRouteImport.update({
  id: '/admin-classifications',
  path: '/admin-classifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/admin-campaigns',
  path: '/admin-campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBundlesRoute = AdminBundlesRouteImport.update({
  id: '/admin-bundles',
  path: '/admin-bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin-banners',
  path: '/admin-banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/admin-backups',
  path: '/admin-backups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAutomationHubRoute = AdminAutomationHubRouteImport.update({
  id: '/admin-automation-hub',
  path: '/admin-automation-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiWhatsappRoute = AdminAiWhatsappRouteImport.update({
  id: '/admin-ai-whatsapp',
  path: '/admin-ai-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiSalesCxRoute = AdminAiSalesCxRouteImport.update({
  id: '/admin-ai-sales-cx',
  path: '/admin-ai-sales-cx',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiProcurementRoute = AdminAiProcurementRouteImport.update({
  id: '/admin-ai-procurement',
  path: '/admin-ai-procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiOrchestratorRoute = AdminAiOrchestratorRouteImport.update({
  id: '/admin-ai-orchestrator',
  path: '/admin-ai-orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiMarketingRoute = AdminAiMarketingRouteImport.update({
  id: '/admin-ai-marketing',
  path: '/admin-ai-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiLoyaltyRoute = AdminAiLoyaltyRouteImport.update({
  id: '/admin-ai-loyalty',
  path: '/admin-ai-loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiInventoryRoute = AdminAiInventoryRouteImport.update({
  id: '/admin-ai-inventory',
  path: '/admin-ai-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiExecutiveDashboardRoute =
  AdminAiExecutiveDashboardRouteImport.update({
    id: '/admin-ai-executive-dashboard',
    path: '/admin-ai-executive-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAiExecutiveRoute = AdminAiExecutiveRouteImport.update({
  id: '/admin-ai-executive',
  path: '/admin-ai-executive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiExcelImportRoute = AdminAiExcelImportRouteImport.update({
  id: '/admin-ai-excel-import',
  path: '/admin-ai-excel-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiChronicRefillRoute = AdminAiChronicRefillRouteImport.update({
  id: '/admin-ai-chronic-refill',
  path: '/admin-ai-chronic-refill',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiCatalogRoute = AdminAiCatalogRouteImport.update({
  id: '/admin-ai-catalog',
  path: '/admin-ai-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin-agents',
  path: '/admin-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsSlugRoute = ConditionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConditionsRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUptimeWebhookRoute = ApiPublicUptimeWebhookRouteImport.update({
  id: '/api/public/uptime-webhook',
  path: '/api/public/uptime-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogErrorRoute = ApiPublicLogErrorRouteImport.update({
  id: '/api/public/log-error',
  path: '/api/public/log-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIncidentCheckRoute = ApiPublicIncidentCheckRouteImport.update({
  id: '/api/public/incident-check',
  path: '/api/public/incident-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgRoute = ApiPublicImgRouteImport.update({
  id: '/api/public/img',
  path: '/api/public/img',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyExecReportRoute =
  ApiPublicHooksWeeklyExecReportRouteImport.update({
    id: '/api/public/hooks/weekly-exec-report',
    path: '/api/public/hooks/weekly-exec-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyAiEnrichRoute =
  ApiPublicHooksWeeklyAiEnrichRouteImport.update({
    id: '/api/public/hooks/weekly-ai-enrich',
    path: '/api/public/hooks/weekly-ai-enrich',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRxMirrorRoute = ApiPublicHooksRxMirrorRouteImport.update({
  id: '/api/public/hooks/rx-mirror',
  path: '/api/public/hooks/rx-mirror',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNightlyIntelRoute =
  ApiPublicHooksNightlyIntelRouteImport.update({
    id: '/api/public/hooks/nightly-intel',
    path: '/api/public/hooks/nightly-intel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksChronicRefillsRoute =
  ApiPublicHooksChronicRefillsRouteImport.update({
    id: '/api/public/hooks/chronic-refills',
    path: '/api/public/hooks/chronic-refills',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAlertsWorkerRoute =
  ApiPublicHooksAlertsWorkerRouteImport.update({
    id: '/api/public/hooks/alerts-worker',
    path: '/api/public/hooks/alerts-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentsWhatsappRoute =
  ApiPublicHooksAgentsWhatsappRouteImport.update({
    id: '/api/public/hooks/agents/whatsapp',
    path: '/api/public/hooks/agents/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentsSalesRoute =
  ApiPublicHooksAgentsSalesRouteImport.update({
    id: '/api/public/hooks/agents/sales',
    path: '/api/public/hooks/agents/sales',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentsOperationsRoute =
  ApiPublicHooksAgentsOperationsRouteImport.update({
    id: '/api/public/hooks/agents/operations',
    path: '/api/public/hooks/agents/operations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentsMarketingRoute =
  ApiPublicHooksAgentsMarketingRouteImport.update({
    id: '/api/public/hooks/agents/marketing',
    path: '/api/public/hooks/agents/marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentsInventoryRoute =
  ApiPublicHooksAgentsInventoryRouteImport.update({
    id: '/api/public/hooks/agents/inventory',
    path: '/api/public/hooks/agents/inventory',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentsCxRoute = ApiPublicHooksAgentsCxRouteImport.update({
  id: '/api/public/hooks/agents/cx',
  path: '/api/public/hooks/agents/cx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAgentsCtoRoute = ApiPublicHooksAgentsCtoRouteImport.update({
  id: '/api/public/hooks/agents/cto',
  path: '/api/public/hooks/agents/cto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAgentsCeoRoute = ApiPublicHooksAgentsCeoRouteImport.update({
  id: '/api/public/hooks/agents/ceo',
  path: '/api/public/hooks/agents/ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAgentsBiRoute = ApiPublicHooksAgentsBiRouteImport.update({
  id: '/api/public/hooks/agents/bi',
  path: '/api/public/hooks/agents/bi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-agents': typeof AdminAgentsRoute
  '/admin-ai-catalog': typeof AdminAiCatalogRoute
  '/admin-ai-chronic-refill': typeof AdminAiChronicRefillRoute
  '/admin-ai-excel-import': typeof AdminAiExcelImportRoute
  '/admin-ai-executive': typeof AdminAiExecutiveRoute
  '/admin-ai-executive-dashboard': typeof AdminAiExecutiveDashboardRoute
  '/admin-ai-inventory': typeof AdminAiInventoryRoute
  '/admin-ai-loyalty': typeof AdminAiLoyaltyRoute
  '/admin-ai-marketing': typeof AdminAiMarketingRoute
  '/admin-ai-orchestrator': typeof AdminAiOrchestratorRoute
  '/admin-ai-procurement': typeof AdminAiProcurementRoute
  '/admin-ai-sales-cx': typeof AdminAiSalesCxRoute
  '/admin-ai-whatsapp': typeof AdminAiWhatsappRoute
  '/admin-automation-hub': typeof AdminAutomationHubRoute
  '/admin-backups': typeof AdminBackupsRoute
  '/admin-banners': typeof AdminBannersRoute
  '/admin-bundles': typeof AdminBundlesRoute
  '/admin-campaigns': typeof AdminCampaignsRoute
  '/admin-classifications': typeof AdminClassificationsRoute
  '/admin-command': typeof AdminCommandRoute
  '/admin-diagnostics': typeof AdminDiagnosticsRoute
  '/admin-discounts': typeof AdminDiscountsRoute
  '/admin-inventory': typeof AdminInventoryRoute
  '/admin-logs': typeof AdminLogsRoute
  '/admin-marketing': typeof AdminMarketingRoute
  '/admin-offers': typeof AdminOffersRoute
  '/admin-products': typeof AdminProductsRoute
  '/admin-rx-check': typeof AdminRxCheckRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/admin-workforce': typeof AdminWorkforceRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/ai-pharmacist': typeof AiPharmacistRoute
  '/ai-prescription': typeof AiPrescriptionRoute
  '/ai-supplement': typeof AiSupplementRoute
  '/ai-symptoms': typeof AiSymptomsRoute
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/conditions': typeof ConditionsRouteWithChildren
  '/insurance': typeof InsuranceRoute
  '/network-health': typeof NetworkHealthRoute
  '/network-test': typeof NetworkTestRoute
  '/prescription': typeof PrescriptionRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/track': typeof TrackRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/yemen-debug': typeof YemenDebugRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/incident-check': typeof ApiPublicIncidentCheckRoute
  '/api/public/log-error': typeof ApiPublicLogErrorRoute
  '/api/public/uptime-webhook': typeof ApiPublicUptimeWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/alerts-worker': typeof ApiPublicHooksAlertsWorkerRoute
  '/api/public/hooks/chronic-refills': typeof ApiPublicHooksChronicRefillsRoute
  '/api/public/hooks/nightly-intel': typeof ApiPublicHooksNightlyIntelRoute
  '/api/public/hooks/rx-mirror': typeof ApiPublicHooksRxMirrorRoute
  '/api/public/hooks/weekly-ai-enrich': typeof ApiPublicHooksWeeklyAiEnrichRoute
  '/api/public/hooks/weekly-exec-report': typeof ApiPublicHooksWeeklyExecReportRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/hooks/agents/bi': typeof ApiPublicHooksAgentsBiRoute
  '/api/public/hooks/agents/ceo': typeof ApiPublicHooksAgentsCeoRoute
  '/api/public/hooks/agents/cto': typeof ApiPublicHooksAgentsCtoRoute
  '/api/public/hooks/agents/cx': typeof ApiPublicHooksAgentsCxRoute
  '/api/public/hooks/agents/inventory': typeof ApiPublicHooksAgentsInventoryRoute
  '/api/public/hooks/agents/marketing': typeof ApiPublicHooksAgentsMarketingRoute
  '/api/public/hooks/agents/operations': typeof ApiPublicHooksAgentsOperationsRoute
  '/api/public/hooks/agents/sales': typeof ApiPublicHooksAgentsSalesRoute
  '/api/public/hooks/agents/whatsapp': typeof ApiPublicHooksAgentsWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-agents': typeof AdminAgentsRoute
  '/admin-ai-catalog': typeof AdminAiCatalogRoute
  '/admin-ai-chronic-refill': typeof AdminAiChronicRefillRoute
  '/admin-ai-excel-import': typeof AdminAiExcelImportRoute
  '/admin-ai-executive': typeof AdminAiExecutiveRoute
  '/admin-ai-executive-dashboard': typeof AdminAiExecutiveDashboardRoute
  '/admin-ai-inventory': typeof AdminAiInventoryRoute
  '/admin-ai-loyalty': typeof AdminAiLoyaltyRoute
  '/admin-ai-marketing': typeof AdminAiMarketingRoute
  '/admin-ai-orchestrator': typeof AdminAiOrchestratorRoute
  '/admin-ai-procurement': typeof AdminAiProcurementRoute
  '/admin-ai-sales-cx': typeof AdminAiSalesCxRoute
  '/admin-ai-whatsapp': typeof AdminAiWhatsappRoute
  '/admin-automation-hub': typeof AdminAutomationHubRoute
  '/admin-backups': typeof AdminBackupsRoute
  '/admin-banners': typeof AdminBannersRoute
  '/admin-bundles': typeof AdminBundlesRoute
  '/admin-campaigns': typeof AdminCampaignsRoute
  '/admin-classifications': typeof AdminClassificationsRoute
  '/admin-command': typeof AdminCommandRoute
  '/admin-diagnostics': typeof AdminDiagnosticsRoute
  '/admin-discounts': typeof AdminDiscountsRoute
  '/admin-inventory': typeof AdminInventoryRoute
  '/admin-logs': typeof AdminLogsRoute
  '/admin-marketing': typeof AdminMarketingRoute
  '/admin-offers': typeof AdminOffersRoute
  '/admin-products': typeof AdminProductsRoute
  '/admin-rx-check': typeof AdminRxCheckRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/admin-workforce': typeof AdminWorkforceRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/ai-pharmacist': typeof AiPharmacistRoute
  '/ai-prescription': typeof AiPrescriptionRoute
  '/ai-supplement': typeof AiSupplementRoute
  '/ai-symptoms': typeof AiSymptomsRoute
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/conditions': typeof ConditionsRouteWithChildren
  '/insurance': typeof InsuranceRoute
  '/network-health': typeof NetworkHealthRoute
  '/network-test': typeof NetworkTestRoute
  '/prescription': typeof PrescriptionRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/track': typeof TrackRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/yemen-debug': typeof YemenDebugRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/incident-check': typeof ApiPublicIncidentCheckRoute
  '/api/public/log-error': typeof ApiPublicLogErrorRoute
  '/api/public/uptime-webhook': typeof ApiPublicUptimeWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/alerts-worker': typeof ApiPublicHooksAlertsWorkerRoute
  '/api/public/hooks/chronic-refills': typeof ApiPublicHooksChronicRefillsRoute
  '/api/public/hooks/nightly-intel': typeof ApiPublicHooksNightlyIntelRoute
  '/api/public/hooks/rx-mirror': typeof ApiPublicHooksRxMirrorRoute
  '/api/public/hooks/weekly-ai-enrich': typeof ApiPublicHooksWeeklyAiEnrichRoute
  '/api/public/hooks/weekly-exec-report': typeof ApiPublicHooksWeeklyExecReportRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/hooks/agents/bi': typeof ApiPublicHooksAgentsBiRoute
  '/api/public/hooks/agents/ceo': typeof ApiPublicHooksAgentsCeoRoute
  '/api/public/hooks/agents/cto': typeof ApiPublicHooksAgentsCtoRoute
  '/api/public/hooks/agents/cx': typeof ApiPublicHooksAgentsCxRoute
  '/api/public/hooks/agents/inventory': typeof ApiPublicHooksAgentsInventoryRoute
  '/api/public/hooks/agents/marketing': typeof ApiPublicHooksAgentsMarketingRoute
  '/api/public/hooks/agents/operations': typeof ApiPublicHooksAgentsOperationsRoute
  '/api/public/hooks/agents/sales': typeof ApiPublicHooksAgentsSalesRoute
  '/api/public/hooks/agents/whatsapp': typeof ApiPublicHooksAgentsWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-agents': typeof AdminAgentsRoute
  '/admin-ai-catalog': typeof AdminAiCatalogRoute
  '/admin-ai-chronic-refill': typeof AdminAiChronicRefillRoute
  '/admin-ai-excel-import': typeof AdminAiExcelImportRoute
  '/admin-ai-executive': typeof AdminAiExecutiveRoute
  '/admin-ai-executive-dashboard': typeof AdminAiExecutiveDashboardRoute
  '/admin-ai-inventory': typeof AdminAiInventoryRoute
  '/admin-ai-loyalty': typeof AdminAiLoyaltyRoute
  '/admin-ai-marketing': typeof AdminAiMarketingRoute
  '/admin-ai-orchestrator': typeof AdminAiOrchestratorRoute
  '/admin-ai-procurement': typeof AdminAiProcurementRoute
  '/admin-ai-sales-cx': typeof AdminAiSalesCxRoute
  '/admin-ai-whatsapp': typeof AdminAiWhatsappRoute
  '/admin-automation-hub': typeof AdminAutomationHubRoute
  '/admin-backups': typeof AdminBackupsRoute
  '/admin-banners': typeof AdminBannersRoute
  '/admin-bundles': typeof AdminBundlesRoute
  '/admin-campaigns': typeof AdminCampaignsRoute
  '/admin-classifications': typeof AdminClassificationsRoute
  '/admin-command': typeof AdminCommandRoute
  '/admin-diagnostics': typeof AdminDiagnosticsRoute
  '/admin-discounts': typeof AdminDiscountsRoute
  '/admin-inventory': typeof AdminInventoryRoute
  '/admin-logs': typeof AdminLogsRoute
  '/admin-marketing': typeof AdminMarketingRoute
  '/admin-offers': typeof AdminOffersRoute
  '/admin-products': typeof AdminProductsRoute
  '/admin-rx-check': typeof AdminRxCheckRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/admin-workforce': typeof AdminWorkforceRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/ai-pharmacist': typeof AiPharmacistRoute
  '/ai-prescription': typeof AiPrescriptionRoute
  '/ai-supplement': typeof AiSupplementRoute
  '/ai-symptoms': typeof AiSymptomsRoute
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/conditions': typeof ConditionsRouteWithChildren
  '/insurance': typeof InsuranceRoute
  '/network-health': typeof NetworkHealthRoute
  '/network-test': typeof NetworkTestRoute
  '/prescription': typeof PrescriptionRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/track': typeof TrackRoute
  '/trust': typeof TrustRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/yemen-debug': typeof YemenDebugRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/incident-check': typeof ApiPublicIncidentCheckRoute
  '/api/public/log-error': typeof ApiPublicLogErrorRoute
  '/api/public/uptime-webhook': typeof ApiPublicUptimeWebhookRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/alerts-worker': typeof ApiPublicHooksAlertsWorkerRoute
  '/api/public/hooks/chronic-refills': typeof ApiPublicHooksChronicRefillsRoute
  '/api/public/hooks/nightly-intel': typeof ApiPublicHooksNightlyIntelRoute
  '/api/public/hooks/rx-mirror': typeof ApiPublicHooksRxMirrorRoute
  '/api/public/hooks/weekly-ai-enrich': typeof ApiPublicHooksWeeklyAiEnrichRoute
  '/api/public/hooks/weekly-exec-report': typeof ApiPublicHooksWeeklyExecReportRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/hooks/agents/bi': typeof ApiPublicHooksAgentsBiRoute
  '/api/public/hooks/agents/ceo': typeof ApiPublicHooksAgentsCeoRoute
  '/api/public/hooks/agents/cto': typeof ApiPublicHooksAgentsCtoRoute
  '/api/public/hooks/agents/cx': typeof ApiPublicHooksAgentsCxRoute
  '/api/public/hooks/agents/inventory': typeof ApiPublicHooksAgentsInventoryRoute
  '/api/public/hooks/agents/marketing': typeof ApiPublicHooksAgentsMarketingRoute
  '/api/public/hooks/agents/operations': typeof ApiPublicHooksAgentsOperationsRoute
  '/api/public/hooks/agents/sales': typeof ApiPublicHooksAgentsSalesRoute
  '/api/public/hooks/agents/whatsapp': typeof ApiPublicHooksAgentsWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-agents'
    | '/admin-ai-catalog'
    | '/admin-ai-chronic-refill'
    | '/admin-ai-excel-import'
    | '/admin-ai-executive'
    | '/admin-ai-executive-dashboard'
    | '/admin-ai-inventory'
    | '/admin-ai-loyalty'
    | '/admin-ai-marketing'
    | '/admin-ai-orchestrator'
    | '/admin-ai-procurement'
    | '/admin-ai-sales-cx'
    | '/admin-ai-whatsapp'
    | '/admin-automation-hub'
    | '/admin-backups'
    | '/admin-banners'
    | '/admin-bundles'
    | '/admin-campaigns'
    | '/admin-classifications'
    | '/admin-command'
    | '/admin-diagnostics'
    | '/admin-discounts'
    | '/admin-inventory'
    | '/admin-logs'
    | '/admin-marketing'
    | '/admin-offers'
    | '/admin-products'
    | '/admin-rx-check'
    | '/admin-settings'
    | '/admin-workforce'
    | '/ai-assistant'
    | '/ai-pharmacist'
    | '/ai-prescription'
    | '/ai-supplement'
    | '/ai-symptoms'
    | '/bundles'
    | '/cart'
    | '/conditions'
    | '/insurance'
    | '/network-health'
    | '/network-test'
    | '/prescription'
    | '/products'
    | '/settings'
    | '/sitemap.xml'
    | '/status'
    | '/track'
    | '/trust'
    | '/unsubscribe'
    | '/yemen-debug'
    | '/conditions/$slug'
    | '/email/unsubscribe'
    | '/product/$id'
    | '/api/public/health'
    | '/api/public/img'
    | '/api/public/incident-check'
    | '/api/public/log-error'
    | '/api/public/uptime-webhook'
    | '/api/public/whatsapp-webhook'
    | '/lovable/email/suppression'
    | '/api/public/hooks/alerts-worker'
    | '/api/public/hooks/chronic-refills'
    | '/api/public/hooks/nightly-intel'
    | '/api/public/hooks/rx-mirror'
    | '/api/public/hooks/weekly-ai-enrich'
    | '/api/public/hooks/weekly-exec-report'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/hooks/agents/bi'
    | '/api/public/hooks/agents/ceo'
    | '/api/public/hooks/agents/cto'
    | '/api/public/hooks/agents/cx'
    | '/api/public/hooks/agents/inventory'
    | '/api/public/hooks/agents/marketing'
    | '/api/public/hooks/agents/operations'
    | '/api/public/hooks/agents/sales'
    | '/api/public/hooks/agents/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-agents'
    | '/admin-ai-catalog'
    | '/admin-ai-chronic-refill'
    | '/admin-ai-excel-import'
    | '/admin-ai-executive'
    | '/admin-ai-executive-dashboard'
    | '/admin-ai-inventory'
    | '/admin-ai-loyalty'
    | '/admin-ai-marketing'
    | '/admin-ai-orchestrator'
    | '/admin-ai-procurement'
    | '/admin-ai-sales-cx'
    | '/admin-ai-whatsapp'
    | '/admin-automation-hub'
    | '/admin-backups'
    | '/admin-banners'
    | '/admin-bundles'
    | '/admin-campaigns'
    | '/admin-classifications'
    | '/admin-command'
    | '/admin-diagnostics'
    | '/admin-discounts'
    | '/admin-inventory'
    | '/admin-logs'
    | '/admin-marketing'
    | '/admin-offers'
    | '/admin-products'
    | '/admin-rx-check'
    | '/admin-settings'
    | '/admin-workforce'
    | '/ai-assistant'
    | '/ai-pharmacist'
    | '/ai-prescription'
    | '/ai-supplement'
    | '/ai-symptoms'
    | '/bundles'
    | '/cart'
    | '/conditions'
    | '/insurance'
    | '/network-health'
    | '/network-test'
    | '/prescription'
    | '/products'
    | '/settings'
    | '/sitemap.xml'
    | '/status'
    | '/track'
    | '/trust'
    | '/unsubscribe'
    | '/yemen-debug'
    | '/conditions/$slug'
    | '/email/unsubscribe'
    | '/product/$id'
    | '/api/public/health'
    | '/api/public/img'
    | '/api/public/incident-check'
    | '/api/public/log-error'
    | '/api/public/uptime-webhook'
    | '/api/public/whatsapp-webhook'
    | '/lovable/email/suppression'
    | '/api/public/hooks/alerts-worker'
    | '/api/public/hooks/chronic-refills'
    | '/api/public/hooks/nightly-intel'
    | '/api/public/hooks/rx-mirror'
    | '/api/public/hooks/weekly-ai-enrich'
    | '/api/public/hooks/weekly-exec-report'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/hooks/agents/bi'
    | '/api/public/hooks/agents/ceo'
    | '/api/public/hooks/agents/cto'
    | '/api/public/hooks/agents/cx'
    | '/api/public/hooks/agents/inventory'
    | '/api/public/hooks/agents/marketing'
    | '/api/public/hooks/agents/operations'
    | '/api/public/hooks/agents/sales'
    | '/api/public/hooks/agents/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-agents'
    | '/admin-ai-catalog'
    | '/admin-ai-chronic-refill'
    | '/admin-ai-excel-import'
    | '/admin-ai-executive'
    | '/admin-ai-executive-dashboard'
    | '/admin-ai-inventory'
    | '/admin-ai-loyalty'
    | '/admin-ai-marketing'
    | '/admin-ai-orchestrator'
    | '/admin-ai-procurement'
    | '/admin-ai-sales-cx'
    | '/admin-ai-whatsapp'
    | '/admin-automation-hub'
    | '/admin-backups'
    | '/admin-banners'
    | '/admin-bundles'
    | '/admin-campaigns'
    | '/admin-classifications'
    | '/admin-command'
    | '/admin-diagnostics'
    | '/admin-discounts'
    | '/admin-inventory'
    | '/admin-logs'
    | '/admin-marketing'
    | '/admin-offers'
    | '/admin-products'
    | '/admin-rx-check'
    | '/admin-settings'
    | '/admin-workforce'
    | '/ai-assistant'
    | '/ai-pharmacist'
    | '/ai-prescription'
    | '/ai-supplement'
    | '/ai-symptoms'
    | '/bundles'
    | '/cart'
    | '/conditions'
    | '/insurance'
    | '/network-health'
    | '/network-test'
    | '/prescription'
    | '/products'
    | '/settings'
    | '/sitemap.xml'
    | '/status'
    | '/track'
    | '/trust'
    | '/unsubscribe'
    | '/yemen-debug'
    | '/conditions/$slug'
    | '/email/unsubscribe'
    | '/product/$id'
    | '/api/public/health'
    | '/api/public/img'
    | '/api/public/incident-check'
    | '/api/public/log-error'
    | '/api/public/uptime-webhook'
    | '/api/public/whatsapp-webhook'
    | '/lovable/email/suppression'
    | '/api/public/hooks/alerts-worker'
    | '/api/public/hooks/chronic-refills'
    | '/api/public/hooks/nightly-intel'
    | '/api/public/hooks/rx-mirror'
    | '/api/public/hooks/weekly-ai-enrich'
    | '/api/public/hooks/weekly-exec-report'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/hooks/agents/bi'
    | '/api/public/hooks/agents/ceo'
    | '/api/public/hooks/agents/cto'
    | '/api/public/hooks/agents/cx'
    | '/api/public/hooks/agents/inventory'
    | '/api/public/hooks/agents/marketing'
    | '/api/public/hooks/agents/operations'
    | '/api/public/hooks/agents/sales'
    | '/api/public/hooks/agents/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAiCatalogRoute: typeof AdminAiCatalogRoute
  AdminAiChronicRefillRoute: typeof AdminAiChronicRefillRoute
  AdminAiExcelImportRoute: typeof AdminAiExcelImportRoute
  AdminAiExecutiveRoute: typeof AdminAiExecutiveRoute
  AdminAiExecutiveDashboardRoute: typeof AdminAiExecutiveDashboardRoute
  AdminAiInventoryRoute: typeof AdminAiInventoryRoute
  AdminAiLoyaltyRoute: typeof AdminAiLoyaltyRoute
  AdminAiMarketingRoute: typeof AdminAiMarketingRoute
  AdminAiOrchestratorRoute: typeof AdminAiOrchestratorRoute
  AdminAiProcurementRoute: typeof AdminAiProcurementRoute
  AdminAiSalesCxRoute: typeof AdminAiSalesCxRoute
  AdminAiWhatsappRoute: typeof AdminAiWhatsappRoute
  AdminAutomationHubRoute: typeof AdminAutomationHubRoute
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBundlesRoute: typeof AdminBundlesRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminClassificationsRoute: typeof AdminClassificationsRoute
  AdminCommandRoute: typeof AdminCommandRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRxCheckRoute: typeof AdminRxCheckRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWorkforceRoute: typeof AdminWorkforceRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AiPharmacistRoute: typeof AiPharmacistRoute
  AiPrescriptionRoute: typeof AiPrescriptionRoute
  AiSupplementRoute: typeof AiSupplementRoute
  AiSymptomsRoute: typeof AiSymptomsRoute
  BundlesRoute: typeof BundlesRoute
  CartRoute: typeof CartRoute
  ConditionsRoute: typeof ConditionsRouteWithChildren
  InsuranceRoute: typeof InsuranceRoute
  NetworkHealthRoute: typeof NetworkHealthRoute
  NetworkTestRoute: typeof NetworkTestRoute
  PrescriptionRoute: typeof PrescriptionRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  TrackRoute: typeof TrackRoute
  TrustRoute: typeof TrustRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  YemenDebugRoute: typeof YemenDebugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicImgRoute: typeof ApiPublicImgRoute
  ApiPublicIncidentCheckRoute: typeof ApiPublicIncidentCheckRoute
  ApiPublicLogErrorRoute: typeof ApiPublicLogErrorRoute
  ApiPublicUptimeWebhookRoute: typeof ApiPublicUptimeWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksAlertsWorkerRoute: typeof ApiPublicHooksAlertsWorkerRoute
  ApiPublicHooksChronicRefillsRoute: typeof ApiPublicHooksChronicRefillsRoute
  ApiPublicHooksNightlyIntelRoute: typeof ApiPublicHooksNightlyIntelRoute
  ApiPublicHooksRxMirrorRoute: typeof ApiPublicHooksRxMirrorRoute
  ApiPublicHooksWeeklyAiEnrichRoute: typeof ApiPublicHooksWeeklyAiEnrichRoute
  ApiPublicHooksWeeklyExecReportRoute: typeof ApiPublicHooksWeeklyExecReportRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicHooksAgentsBiRoute: typeof ApiPublicHooksAgentsBiRoute
  ApiPublicHooksAgentsCeoRoute: typeof ApiPublicHooksAgentsCeoRoute
  ApiPublicHooksAgentsCtoRoute: typeof ApiPublicHooksAgentsCtoRoute
  ApiPublicHooksAgentsCxRoute: typeof ApiPublicHooksAgentsCxRoute
  ApiPublicHooksAgentsInventoryRoute: typeof ApiPublicHooksAgentsInventoryRoute
  ApiPublicHooksAgentsMarketingRoute: typeof ApiPublicHooksAgentsMarketingRoute
  ApiPublicHooksAgentsOperationsRoute: typeof ApiPublicHooksAgentsOperationsRoute
  ApiPublicHooksAgentsSalesRoute: typeof ApiPublicHooksAgentsSalesRoute
  ApiPublicHooksAgentsWhatsappRoute: typeof ApiPublicHooksAgentsWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yemen-debug': {
      id: '/yemen-debug'
      path: '/yemen-debug'
      fullPath: '/yemen-debug'
      preLoaderRoute: typeof YemenDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription': {
      id: '/prescription'
      path: '/prescription'
      fullPath: '/prescription'
      preLoaderRoute: typeof PrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-test': {
      id: '/network-test'
      path: '/network-test'
      fullPath: '/network-test'
      preLoaderRoute: typeof NetworkTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-health': {
      id: '/network-health'
      path: '/network-health'
      fullPath: '/network-health'
      preLoaderRoute: typeof NetworkHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-symptoms': {
      id: '/ai-symptoms'
      path: '/ai-symptoms'
      fullPath: '/ai-symptoms'
      preLoaderRoute: typeof AiSymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-supplement': {
      id: '/ai-supplement'
      path: '/ai-supplement'
      fullPath: '/ai-supplement'
      preLoaderRoute: typeof AiSupplementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-prescription': {
      id: '/ai-prescription'
      path: '/ai-prescription'
      fullPath: '/ai-prescription'
      preLoaderRoute: typeof AiPrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-pharmacist': {
      id: '/ai-pharmacist'
      path: '/ai-pharmacist'
      fullPath: '/ai-pharmacist'
      preLoaderRoute: typeof AiPharmacistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-workforce': {
      id: '/admin-workforce'
      path: '/admin-workforce'
      fullPath: '/admin-workforce'
      preLoaderRoute: typeof AdminWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-settings': {
      id: '/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-rx-check': {
      id: '/admin-rx-check'
      path: '/admin-rx-check'
      fullPath: '/admin-rx-check'
      preLoaderRoute: typeof AdminRxCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-products': {
      id: '/admin-products'
      path: '/admin-products'
      fullPath: '/admin-products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-offers': {
      id: '/admin-offers'
      path: '/admin-offers'
      fullPath: '/admin-offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-marketing': {
      id: '/admin-marketing'
      path: '/admin-marketing'
      fullPath: '/admin-marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-logs': {
      id: '/admin-logs'
      path: '/admin-logs'
      fullPath: '/admin-logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-inventory': {
      id: '/admin-inventory'
      path: '/admin-inventory'
      fullPath: '/admin-inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-discounts': {
      id: '/admin-discounts'
      path: '/admin-discounts'
      fullPath: '/admin-discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-diagnostics': {
      id: '/admin-diagnostics'
      path: '/admin-diagnostics'
      fullPath: '/admin-diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-command': {
      id: '/admin-command'
      path: '/admin-command'
      fullPath: '/admin-command'
      preLoaderRoute: typeof AdminCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-classifications': {
      id: '/admin-classifications'
      path: '/admin-classifications'
      fullPath: '/admin-classifications'
      preLoaderRoute: typeof AdminClassificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-campaigns': {
      id: '/admin-campaigns'
      path: '/admin-campaigns'
      fullPath: '/admin-campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-bundles': {
      id: '/admin-bundles'
      path: '/admin-bundles'
      fullPath: '/admin-bundles'
      preLoaderRoute: typeof AdminBundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-banners': {
      id: '/admin-banners'
      path: '/admin-banners'
      fullPath: '/admin-banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-backups': {
      id: '/admin-backups'
      path: '/admin-backups'
      fullPath: '/admin-backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-automation-hub': {
      id: '/admin-automation-hub'
      path: '/admin-automation-hub'
      fullPath: '/admin-automation-hub'
      preLoaderRoute: typeof AdminAutomationHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-whatsapp': {
      id: '/admin-ai-whatsapp'
      path: '/admin-ai-whatsapp'
      fullPath: '/admin-ai-whatsapp'
      preLoaderRoute: typeof AdminAiWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-sales-cx': {
      id: '/admin-ai-sales-cx'
      path: '/admin-ai-sales-cx'
      fullPath: '/admin-ai-sales-cx'
      preLoaderRoute: typeof AdminAiSalesCxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-procurement': {
      id: '/admin-ai-procurement'
      path: '/admin-ai-procurement'
      fullPath: '/admin-ai-procurement'
      preLoaderRoute: typeof AdminAiProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-orchestrator': {
      id: '/admin-ai-orchestrator'
      path: '/admin-ai-orchestrator'
      fullPath: '/admin-ai-orchestrator'
      preLoaderRoute: typeof AdminAiOrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-marketing': {
      id: '/admin-ai-marketing'
      path: '/admin-ai-marketing'
      fullPath: '/admin-ai-marketing'
      preLoaderRoute: typeof AdminAiMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-loyalty': {
      id: '/admin-ai-loyalty'
      path: '/admin-ai-loyalty'
      fullPath: '/admin-ai-loyalty'
      preLoaderRoute: typeof AdminAiLoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-inventory': {
      id: '/admin-ai-inventory'
      path: '/admin-ai-inventory'
      fullPath: '/admin-ai-inventory'
      preLoaderRoute: typeof AdminAiInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-executive-dashboard': {
      id: '/admin-ai-executive-dashboard'
      path: '/admin-ai-executive-dashboard'
      fullPath: '/admin-ai-executive-dashboard'
      preLoaderRoute: typeof AdminAiExecutiveDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-executive': {
      id: '/admin-ai-executive'
      path: '/admin-ai-executive'
      fullPath: '/admin-ai-executive'
      preLoaderRoute: typeof AdminAiExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-excel-import': {
      id: '/admin-ai-excel-import'
      path: '/admin-ai-excel-import'
      fullPath: '/admin-ai-excel-import'
      preLoaderRoute: typeof AdminAiExcelImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-chronic-refill': {
      id: '/admin-ai-chronic-refill'
      path: '/admin-ai-chronic-refill'
      fullPath: '/admin-ai-chronic-refill'
      preLoaderRoute: typeof AdminAiChronicRefillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-catalog': {
      id: '/admin-ai-catalog'
      path: '/admin-ai-catalog'
      fullPath: '/admin-ai-catalog'
      preLoaderRoute: typeof AdminAiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-agents': {
      id: '/admin-agents'
      path: '/admin-agents'
      fullPath: '/admin-agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/$slug': {
      id: '/conditions/$slug'
      path: '/$slug'
      fullPath: '/conditions/$slug'
      preLoaderRoute: typeof ConditionsSlugRouteImport
      parentRoute: typeof ConditionsRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/uptime-webhook': {
      id: '/api/public/uptime-webhook'
      path: '/api/public/uptime-webhook'
      fullPath: '/api/public/uptime-webhook'
      preLoaderRoute: typeof ApiPublicUptimeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/log-error': {
      id: '/api/public/log-error'
      path: '/api/public/log-error'
      fullPath: '/api/public/log-error'
      preLoaderRoute: typeof ApiPublicLogErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/incident-check': {
      id: '/api/public/incident-check'
      path: '/api/public/incident-check'
      fullPath: '/api/public/incident-check'
      preLoaderRoute: typeof ApiPublicIncidentCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img': {
      id: '/api/public/img'
      path: '/api/public/img'
      fullPath: '/api/public/img'
      preLoaderRoute: typeof ApiPublicImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-exec-report': {
      id: '/api/public/hooks/weekly-exec-report'
      path: '/api/public/hooks/weekly-exec-report'
      fullPath: '/api/public/hooks/weekly-exec-report'
      preLoaderRoute: typeof ApiPublicHooksWeeklyExecReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-ai-enrich': {
      id: '/api/public/hooks/weekly-ai-enrich'
      path: '/api/public/hooks/weekly-ai-enrich'
      fullPath: '/api/public/hooks/weekly-ai-enrich'
      preLoaderRoute: typeof ApiPublicHooksWeeklyAiEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rx-mirror': {
      id: '/api/public/hooks/rx-mirror'
      path: '/api/public/hooks/rx-mirror'
      fullPath: '/api/public/hooks/rx-mirror'
      preLoaderRoute: typeof ApiPublicHooksRxMirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nightly-intel': {
      id: '/api/public/hooks/nightly-intel'
      path: '/api/public/hooks/nightly-intel'
      fullPath: '/api/public/hooks/nightly-intel'
      preLoaderRoute: typeof ApiPublicHooksNightlyIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/chronic-refills': {
      id: '/api/public/hooks/chronic-refills'
      path: '/api/public/hooks/chronic-refills'
      fullPath: '/api/public/hooks/chronic-refills'
      preLoaderRoute: typeof ApiPublicHooksChronicRefillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/alerts-worker': {
      id: '/api/public/hooks/alerts-worker'
      path: '/api/public/hooks/alerts-worker'
      fullPath: '/api/public/hooks/alerts-worker'
      preLoaderRoute: typeof ApiPublicHooksAlertsWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agents/whatsapp': {
      id: '/api/public/hooks/agents/whatsapp'
      path: '/api/public/hooks/agents/whatsapp'
      fullPath: '/api/public/hooks/agents/whatsapp'
      preLoaderRoute: typeof ApiPublicHooksAgentsWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agents/sales': {
      id: '/api/public/hooks/agents/sales'
      path: '/api/public/hooks/agents/sales'
      fullPath: '/api/public/hooks/agents/sales'
      preLoaderRoute: typeof ApiPublicHooksAgentsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agents/operations': {
      id: '/api/public/hooks/agents/operations'
      path: '/api/public/hooks/agents/operations'
      fullPath: '/api/public/hooks/agents/operations'
      preLoaderRoute: typeof ApiPublicHooksAgentsOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agents/marketing': {
      id: '/api/public/hooks/agents/marketing'
      path: '/api/public/hooks/agents/marketing'
      fullPath: '/api/public/hooks/agents/marketing'
      preLoaderRoute: typeof ApiPublicHooksAgentsMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agents/inventory': {
      id: '/api/public/hooks/agents/inventory'
      path: '/api/public/hooks/agents/inventory'
      fullPath: '/api/public/hooks/agents/inventory'
      preLoaderRoute: typeof ApiPublicHooksAgentsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agents/cx': {
      id: '/api/public/hooks/agents/cx'
      path: '/api/public/hooks/agents/cx'
      fullPath: '/api/public/hooks/agents/cx'
      preLoaderRoute: typeof ApiPublicHooksAgentsCxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agents/cto': {
      id: '/api/public/hooks/agents/cto'
      path: '/api/public/hooks/agents/cto'
      fullPath: '/api/public/hooks/agents/cto'
      preLoaderRoute: typeof ApiPublicHooksAgentsCtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agents/ceo': {
      id: '/api/public/hooks/agents/ceo'
      path: '/api/public/hooks/agents/ceo'
      fullPath: '/api/public/hooks/agents/ceo'
      preLoaderRoute: typeof ApiPublicHooksAgentsCeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agents/bi': {
      id: '/api/public/hooks/agents/bi'
      path: '/api/public/hooks/agents/bi'
      fullPath: '/api/public/hooks/agents/bi'
      preLoaderRoute: typeof ApiPublicHooksAgentsBiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConditionsRouteChildren {
  ConditionsSlugRoute: typeof ConditionsSlugRoute
}

const ConditionsRouteChildren: ConditionsRouteChildren = {
  ConditionsSlugRoute: ConditionsSlugRoute,
}

const ConditionsRouteWithChildren = ConditionsRoute._addFileChildren(
  ConditionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAiCatalogRoute: AdminAiCatalogRoute,
  AdminAiChronicRefillRoute: AdminAiChronicRefillRoute,
  AdminAiExcelImportRoute: AdminAiExcelImportRoute,
  AdminAiExecutiveRoute: AdminAiExecutiveRoute,
  AdminAiExecutiveDashboardRoute: AdminAiExecutiveDashboardRoute,
  AdminAiInventoryRoute: AdminAiInventoryRoute,
  AdminAiLoyaltyRoute: AdminAiLoyaltyRoute,
  AdminAiMarketingRoute: AdminAiMarketingRoute,
  AdminAiOrchestratorRoute: AdminAiOrchestratorRoute,
  AdminAiProcurementRoute: AdminAiProcurementRoute,
  AdminAiSalesCxRoute: AdminAiSalesCxRoute,
  AdminAiWhatsappRoute: AdminAiWhatsappRoute,
  AdminAutomationHubRoute: AdminAutomationHubRoute,
  AdminBackupsRoute: AdminBackupsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBundlesRoute: AdminBundlesRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminClassificationsRoute: AdminClassificationsRoute,
  AdminCommandRoute: AdminCommandRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRxCheckRoute: AdminRxCheckRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWorkforceRoute: AdminWorkforceRoute,
  AiAssistantRoute: AiAssistantRoute,
  AiPharmacistRoute: AiPharmacistRoute,
  AiPrescriptionRoute: AiPrescriptionRoute,
  AiSupplementRoute: AiSupplementRoute,
  AiSymptomsRoute: AiSymptomsRoute,
  BundlesRoute: BundlesRoute,
  CartRoute: CartRoute,
  ConditionsRoute: ConditionsRouteWithChildren,
  InsuranceRoute: InsuranceRoute,
  NetworkHealthRoute: NetworkHealthRoute,
  NetworkTestRoute: NetworkTestRoute,
  PrescriptionRoute: PrescriptionRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  TrackRoute: TrackRoute,
  TrustRoute: TrustRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  YemenDebugRoute: YemenDebugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicImgRoute: ApiPublicImgRoute,
  ApiPublicIncidentCheckRoute: ApiPublicIncidentCheckRoute,
  ApiPublicLogErrorRoute: ApiPublicLogErrorRoute,
  ApiPublicUptimeWebhookRoute: ApiPublicUptimeWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksAlertsWorkerRoute: ApiPublicHooksAlertsWorkerRoute,
  ApiPublicHooksChronicRefillsRoute: ApiPublicHooksChronicRefillsRoute,
  ApiPublicHooksNightlyIntelRoute: ApiPublicHooksNightlyIntelRoute,
  ApiPublicHooksRxMirrorRoute: ApiPublicHooksRxMirrorRoute,
  ApiPublicHooksWeeklyAiEnrichRoute: ApiPublicHooksWeeklyAiEnrichRoute,
  ApiPublicHooksWeeklyExecReportRoute: ApiPublicHooksWeeklyExecReportRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicHooksAgentsBiRoute: ApiPublicHooksAgentsBiRoute,
  ApiPublicHooksAgentsCeoRoute: ApiPublicHooksAgentsCeoRoute,
  ApiPublicHooksAgentsCtoRoute: ApiPublicHooksAgentsCtoRoute,
  ApiPublicHooksAgentsCxRoute: ApiPublicHooksAgentsCxRoute,
  ApiPublicHooksAgentsInventoryRoute: ApiPublicHooksAgentsInventoryRoute,
  ApiPublicHooksAgentsMarketingRoute: ApiPublicHooksAgentsMarketingRoute,
  ApiPublicHooksAgentsOperationsRoute: ApiPublicHooksAgentsOperationsRoute,
  ApiPublicHooksAgentsSalesRoute: ApiPublicHooksAgentsSalesRoute,
  ApiPublicHooksAgentsWhatsappRoute: ApiPublicHooksAgentsWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
