/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAiRuntimeRouteImport } from './routes/_authenticated/ai-runtime'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDispensesRouteImport } from './routes/_authenticated/dispenses'
import { Route as AuthenticatedDoctorsRouteImport } from './routes/_authenticated/doctors'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedPrescriptionsRouteImport } from './routes/_authenticated/prescriptions'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as PlanetPlanetIdRouteImport } from './routes/planet.$planetId'
import { Route as AuthenticatedCatalogIndexRouteImport } from './routes/_authenticated/catalog.index'
import { Route as AuthenticatedCatalogProductIdRouteImport } from './routes/_authenticated/catalog.$productId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedDispensesDispenseIdRouteImport } from './routes/_authenticated/dispenses.$dispenseId'
import { Route as AuthenticatedDoctorsDoctorIdRouteImport } from './routes/_authenticated/doctors.$doctorId'
import { Route as AuthenticatedInsuranceIndexRouteImport } from './routes/_authenticated/insurance.index'
import { Route as AuthenticatedInsuranceClaimsRouteImport } from './routes/_authenticated/insurance.claims'
import { Route as AuthenticatedInsuranceCoverageRouteImport } from './routes/_authenticated/insurance.coverage'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'
import { Route as AuthenticatedPrescriptionsPrescriptionIdRouteImport } from './routes/_authenticated/prescriptions.$prescriptionId'
import { Route as AuthenticatedPurchaseOrdersIdRouteImport } from './routes/_authenticated/purchase-orders.$id'
import { Route as AuthenticatedInsuranceClaimsClaimIdRouteImport } from './routes/_authenticated/insurance.claims_.$claimId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiRuntimeRoute = AuthenticatedAiRuntimeRouteImport.update({
  id: '/ai-runtime',
  path: '/ai-runtime',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispensesRoute = AuthenticatedDispensesRouteImport.update({
  id: '/dispenses',
  path: '/dispenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorsRoute = AuthenticatedDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrescriptionsRoute =
  AuthenticatedPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlanetPlanetIdRoute = PlanetPlanetIdRouteImport.update({
  id: '/planet/$planetId',
  path: '/planet/$planetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCatalogIndexRoute =
  AuthenticatedCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductIdRoute =
  AuthenticatedCatalogProductIdRouteImport.update({
    id: '/catalog/$productId',
    path: '/catalog/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedDispensesDispenseIdRoute =
  AuthenticatedDispensesDispenseIdRouteImport.update({
    id: '/$dispenseId',
    path: '/$dispenseId',
    getParentRoute: () => AuthenticatedDispensesRoute,
  } as any)
const AuthenticatedDoctorsDoctorIdRoute =
  AuthenticatedDoctorsDoctorIdRouteImport.update({
    id: '/$doctorId',
    path: '/$doctorId',
    getParentRoute: () => AuthenticatedDoctorsRoute,
  } as any)
const AuthenticatedInsuranceIndexRoute =
  AuthenticatedInsuranceIndexRouteImport.update({
    id: '/insurance/',
    path: '/insurance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsuranceClaimsRoute =
  AuthenticatedInsuranceClaimsRouteImport.update({
    id: '/insurance/claims',
    path: '/insurance/claims',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsuranceCoverageRoute =
  AuthenticatedInsuranceCoverageRouteImport.update({
    id: '/insurance/coverage',
    path: '/insurance/coverage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedPrescriptionsPrescriptionIdRoute =
  AuthenticatedPrescriptionsPrescriptionIdRouteImport.update({
    id: '/$prescriptionId',
    path: '/$prescriptionId',
    getParentRoute: () => AuthenticatedPrescriptionsRoute,
  } as any)
const AuthenticatedPurchaseOrdersIdRoute =
  AuthenticatedPurchaseOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPurchaseOrdersRoute,
  } as any)
const AuthenticatedInsuranceClaimsClaimIdRoute =
  AuthenticatedInsuranceClaimsClaimIdRouteImport.update({
    id: '/insurance/claims_/$claimId',
    path: '/insurance/claims/$claimId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/mission-control': typeof MissionControlRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-runtime': typeof AuthenticatedAiRuntimeRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dispenses': typeof AuthenticatedDispensesRouteWithChildren
  '/doctors': typeof AuthenticatedDoctorsRouteWithChildren
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/prescriptions': typeof AuthenticatedPrescriptionsRouteWithChildren
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/planet/$planetId': typeof PlanetPlanetIdRoute
  '/catalog/$productId': typeof AuthenticatedCatalogProductIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/dispenses/$dispenseId': typeof AuthenticatedDispensesDispenseIdRoute
  '/doctors/$doctorId': typeof AuthenticatedDoctorsDoctorIdRoute
  '/insurance/claims': typeof AuthenticatedInsuranceClaimsRoute
  '/insurance/coverage': typeof AuthenticatedInsuranceCoverageRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/insurance/': typeof AuthenticatedInsuranceIndexRoute
  '/insurance/claims/$claimId': typeof AuthenticatedInsuranceClaimsClaimIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/mission-control': typeof MissionControlRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-runtime': typeof AuthenticatedAiRuntimeRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dispenses': typeof AuthenticatedDispensesRouteWithChildren
  '/doctors': typeof AuthenticatedDoctorsRouteWithChildren
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/prescriptions': typeof AuthenticatedPrescriptionsRouteWithChildren
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/planet/$planetId': typeof PlanetPlanetIdRoute
  '/catalog/$productId': typeof AuthenticatedCatalogProductIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/dispenses/$dispenseId': typeof AuthenticatedDispensesDispenseIdRoute
  '/doctors/$doctorId': typeof AuthenticatedDoctorsDoctorIdRoute
  '/insurance/claims': typeof AuthenticatedInsuranceClaimsRoute
  '/insurance/coverage': typeof AuthenticatedInsuranceCoverageRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/catalog': typeof AuthenticatedCatalogIndexRoute
  '/insurance': typeof AuthenticatedInsuranceIndexRoute
  '/insurance/claims/$claimId': typeof AuthenticatedInsuranceClaimsClaimIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/mission-control': typeof MissionControlRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ai-runtime': typeof AuthenticatedAiRuntimeRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dispenses': typeof AuthenticatedDispensesRouteWithChildren
  '/_authenticated/doctors': typeof AuthenticatedDoctorsRouteWithChildren
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/prescriptions': typeof AuthenticatedPrescriptionsRouteWithChildren
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteWithChildren
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/planet/$planetId': typeof PlanetPlanetIdRoute
  '/_authenticated/catalog/$productId': typeof AuthenticatedCatalogProductIdRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/dispenses/$dispenseId': typeof AuthenticatedDispensesDispenseIdRoute
  '/_authenticated/doctors/$doctorId': typeof AuthenticatedDoctorsDoctorIdRoute
  '/_authenticated/insurance/claims': typeof AuthenticatedInsuranceClaimsRoute
  '/_authenticated/insurance/coverage': typeof AuthenticatedInsuranceCoverageRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/prescriptions/$prescriptionId': typeof AuthenticatedPrescriptionsPrescriptionIdRoute
  '/_authenticated/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/_authenticated/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/_authenticated/insurance/': typeof AuthenticatedInsuranceIndexRoute
  '/_authenticated/insurance/claims_/$claimId': typeof AuthenticatedInsuranceClaimsClaimIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chat'
    | '/auth'
    | '/mission-control'
    | '/reset-password'
    | '/ai-runtime'
    | '/customers'
    | '/dispenses'
    | '/doctors'
    | '/patients'
    | '/prescriptions'
    | '/purchase-orders'
    | '/suppliers'
    | '/warehouses'
    | '/planet/$planetId'
    | '/catalog/$productId'
    | '/customers/$customerId'
    | '/dispenses/$dispenseId'
    | '/doctors/$doctorId'
    | '/insurance/claims'
    | '/insurance/coverage'
    | '/patients/$patientId'
    | '/prescriptions/$prescriptionId'
    | '/purchase-orders/$id'
    | '/catalog/'
    | '/insurance/'
    | '/insurance/claims/$claimId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/auth'
    | '/mission-control'
    | '/reset-password'
    | '/ai-runtime'
    | '/customers'
    | '/dispenses'
    | '/doctors'
    | '/patients'
    | '/prescriptions'
    | '/purchase-orders'
    | '/suppliers'
    | '/warehouses'
    | '/planet/$planetId'
    | '/catalog/$productId'
    | '/customers/$customerId'
    | '/dispenses/$dispenseId'
    | '/doctors/$doctorId'
    | '/insurance/claims'
    | '/insurance/coverage'
    | '/patients/$patientId'
    | '/prescriptions/$prescriptionId'
    | '/purchase-orders/$id'
    | '/catalog'
    | '/insurance'
    | '/insurance/claims/$claimId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-chat'
    | '/auth'
    | '/mission-control'
    | '/reset-password'
    | '/_authenticated/ai-runtime'
    | '/_authenticated/customers'
    | '/_authenticated/dispenses'
    | '/_authenticated/doctors'
    | '/_authenticated/patients'
    | '/_authenticated/prescriptions'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/suppliers'
    | '/_authenticated/warehouses'
    | '/planet/$planetId'
    | '/_authenticated/catalog/$productId'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/dispenses/$dispenseId'
    | '/_authenticated/doctors/$doctorId'
    | '/_authenticated/insurance/claims'
    | '/_authenticated/insurance/coverage'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/prescriptions/$prescriptionId'
    | '/_authenticated/purchase-orders/$id'
    | '/_authenticated/catalog/'
    | '/_authenticated/insurance/'
    | '/_authenticated/insurance/claims_/$claimId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiChatRoute: typeof AiChatRoute
  AuthRoute: typeof AuthRoute
  MissionControlRoute: typeof MissionControlRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PlanetPlanetIdRoute: typeof PlanetPlanetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-runtime': {
      id: '/_authenticated/ai-runtime'
      path: '/ai-runtime'
      fullPath: '/ai-runtime'
      preLoaderRoute: typeof AuthenticatedAiRuntimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispenses': {
      id: '/_authenticated/dispenses'
      path: '/dispenses'
      fullPath: '/dispenses'
      preLoaderRoute: typeof AuthenticatedDispensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors': {
      id: '/_authenticated/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prescriptions': {
      id: '/_authenticated/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AuthenticatedPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/planet/$planetId': {
      id: '/planet/$planetId'
      path: '/planet/$planetId'
      fullPath: '/planet/$planetId'
      preLoaderRoute: typeof PlanetPlanetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/catalog/': {
      id: '/_authenticated/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AuthenticatedCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/$productId': {
      id: '/_authenticated/catalog/$productId'
      path: '/catalog/$productId'
      fullPath: '/catalog/$productId'
      preLoaderRoute: typeof AuthenticatedCatalogProductIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/dispenses/$dispenseId': {
      id: '/_authenticated/dispenses/$dispenseId'
      path: '/$dispenseId'
      fullPath: '/dispenses/$dispenseId'
      preLoaderRoute: typeof AuthenticatedDispensesDispenseIdRouteImport
      parentRoute: typeof AuthenticatedDispensesRoute
    }
    '/_authenticated/doctors/$doctorId': {
      id: '/_authenticated/doctors/$doctorId'
      path: '/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof AuthenticatedDoctorsDoctorIdRouteImport
      parentRoute: typeof AuthenticatedDoctorsRoute
    }
    '/_authenticated/insurance/': {
      id: '/_authenticated/insurance/'
      path: '/insurance'
      fullPath: '/insurance/'
      preLoaderRoute: typeof AuthenticatedInsuranceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurance/claims': {
      id: '/_authenticated/insurance/claims'
      path: '/insurance/claims'
      fullPath: '/insurance/claims'
      preLoaderRoute: typeof AuthenticatedInsuranceClaimsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurance/coverage': {
      id: '/_authenticated/insurance/coverage'
      path: '/insurance/coverage'
      fullPath: '/insurance/coverage'
      preLoaderRoute: typeof AuthenticatedInsuranceCoverageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/prescriptions/$prescriptionId': {
      id: '/_authenticated/prescriptions/$prescriptionId'
      path: '/$prescriptionId'
      fullPath: '/prescriptions/$prescriptionId'
      preLoaderRoute: typeof AuthenticatedPrescriptionsPrescriptionIdRouteImport
      parentRoute: typeof AuthenticatedPrescriptionsRoute
    }
    '/_authenticated/purchase-orders/$id': {
      id: '/_authenticated/purchase-orders/$id'
      path: '/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedPurchaseOrdersRoute
    }
    '/_authenticated/insurance/claims_/$claimId': {
      id: '/_authenticated/insurance/claims_/$claimId'
      path: '/insurance/claims/$claimId'
      fullPath: '/insurance/claims/$claimId'
      preLoaderRoute: typeof AuthenticatedInsuranceClaimsClaimIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRoute:
      AuthenticatedCustomersCustomerIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedDispensesRouteChildren {
  AuthenticatedDispensesDispenseIdRoute: typeof AuthenticatedDispensesDispenseIdRoute
}

const AuthenticatedDispensesRouteChildren: AuthenticatedDispensesRouteChildren =
  {
    AuthenticatedDispensesDispenseIdRoute:
      AuthenticatedDispensesDispenseIdRoute,
  }

const AuthenticatedDispensesRouteWithChildren =
  AuthenticatedDispensesRoute._addFileChildren(
    AuthenticatedDispensesRouteChildren,
  )

interface AuthenticatedDoctorsRouteChildren {
  AuthenticatedDoctorsDoctorIdRoute: typeof AuthenticatedDoctorsDoctorIdRoute
}

const AuthenticatedDoctorsRouteChildren: AuthenticatedDoctorsRouteChildren = {
  AuthenticatedDoctorsDoctorIdRoute: AuthenticatedDoctorsDoctorIdRoute,
}

const AuthenticatedDoctorsRouteWithChildren =
  AuthenticatedDoctorsRoute._addFileChildren(AuthenticatedDoctorsRouteChildren)

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedPrescriptionsRouteChildren {
  AuthenticatedPrescriptionsPrescriptionIdRoute: typeof AuthenticatedPrescriptionsPrescriptionIdRoute
}

const AuthenticatedPrescriptionsRouteChildren: AuthenticatedPrescriptionsRouteChildren =
  {
    AuthenticatedPrescriptionsPrescriptionIdRoute:
      AuthenticatedPrescriptionsPrescriptionIdRoute,
  }

const AuthenticatedPrescriptionsRouteWithChildren =
  AuthenticatedPrescriptionsRoute._addFileChildren(
    AuthenticatedPrescriptionsRouteChildren,
  )

interface AuthenticatedPurchaseOrdersRouteChildren {
  AuthenticatedPurchaseOrdersIdRoute: typeof AuthenticatedPurchaseOrdersIdRoute
}

const AuthenticatedPurchaseOrdersRouteChildren: AuthenticatedPurchaseOrdersRouteChildren =
  {
    AuthenticatedPurchaseOrdersIdRoute: AuthenticatedPurchaseOrdersIdRoute,
  }

const AuthenticatedPurchaseOrdersRouteWithChildren =
  AuthenticatedPurchaseOrdersRoute._addFileChildren(
    AuthenticatedPurchaseOrdersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiRuntimeRoute: typeof AuthenticatedAiRuntimeRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDispensesRoute: typeof AuthenticatedDispensesRouteWithChildren
  AuthenticatedDoctorsRoute: typeof AuthenticatedDoctorsRouteWithChildren
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
  AuthenticatedPrescriptionsRoute: typeof AuthenticatedPrescriptionsRouteWithChildren
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRouteWithChildren
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
  AuthenticatedCatalogProductIdRoute: typeof AuthenticatedCatalogProductIdRoute
  AuthenticatedInsuranceClaimsRoute: typeof AuthenticatedInsuranceClaimsRoute
  AuthenticatedInsuranceCoverageRoute: typeof AuthenticatedInsuranceCoverageRoute
  AuthenticatedCatalogIndexRoute: typeof AuthenticatedCatalogIndexRoute
  AuthenticatedInsuranceIndexRoute: typeof AuthenticatedInsuranceIndexRoute
  AuthenticatedInsuranceClaimsClaimIdRoute: typeof AuthenticatedInsuranceClaimsClaimIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiRuntimeRoute: AuthenticatedAiRuntimeRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDispensesRoute: AuthenticatedDispensesRouteWithChildren,
  AuthenticatedDoctorsRoute: AuthenticatedDoctorsRouteWithChildren,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
  AuthenticatedPrescriptionsRoute: AuthenticatedPrescriptionsRouteWithChildren,
  AuthenticatedPurchaseOrdersRoute:
    AuthenticatedPurchaseOrdersRouteWithChildren,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
  AuthenticatedCatalogProductIdRoute: AuthenticatedCatalogProductIdRoute,
  AuthenticatedInsuranceClaimsRoute: AuthenticatedInsuranceClaimsRoute,
  AuthenticatedInsuranceCoverageRoute: AuthenticatedInsuranceCoverageRoute,
  AuthenticatedCatalogIndexRoute: AuthenticatedCatalogIndexRoute,
  AuthenticatedInsuranceIndexRoute: AuthenticatedInsuranceIndexRoute,
  AuthenticatedInsuranceClaimsClaimIdRoute:
    AuthenticatedInsuranceClaimsClaimIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiChatRoute: AiChatRoute,
  AuthRoute: AuthRoute,
  MissionControlRoute: MissionControlRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PlanetPlanetIdRoute: PlanetPlanetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
