/**
 * AI SUN CORE — canonical event type registry.
 * Add new events here; router + agents dispatch off these constants.
 */
export const AI_EVENTS = {
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_PAID: "ORDER_PAID",
  SALES_ORDER_CREATED: "SALES_ORDER_CREATED",
  PRESCRIPTION_UPLOADED: "PRESCRIPTION_UPLOADED",
  STOCK_LOW: "STOCK_LOW",
  LOW_STOCK_PREDICTED: "LOW_STOCK_PREDICTED",
  PURCHASE_RECOMMENDED: "PURCHASE_RECOMMENDED",
  DEAD_STOCK_DETECTED: "DEAD_STOCK_DETECTED",
  EXPIRY_WARNING: "EXPIRY_WARNING",
  CUSTOMER_MESSAGE: "CUSTOMER_MESSAGE",
  WHATSAPP_INBOUND: "WHATSAPP_INBOUND",
  SECURITY_ALERT: "SECURITY_ALERT",
  // Phase 6 — Business Intelligence
  DAILY_REPORT: "DAILY_REPORT",
  SALES_DROP: "SALES_DROP",
  PROFIT_CHANGE: "PROFIT_CHANGE",
  GROWTH_OPPORTUNITY: "GROWTH_OPPORTUNITY",
  FORECAST_READY: "FORECAST_READY",
  // Phase 7 — Security Guardian
  LOGIN_FAILED: "LOGIN_FAILED",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  RLS_VIOLATION: "RLS_VIOLATION",
  SUSPICIOUS_QUERY: "SUSPICIOUS_QUERY",
  SECRET_EXPOSURE: "SECRET_EXPOSURE",
  SYSTEM_ANOMALY: "SYSTEM_ANOMALY",
} as const;

export type AIEventType = (typeof AI_EVENTS)[keyof typeof AI_EVENTS];
